language: node_js
os:
  - osx
env:
  - CXX=g++
node_js:
  "node"
before_script:
  - brew install librsvg
  - npm install -g prebuild
install:
  - npm install
script:
  - npm run prebuild

addons:
  artifacts:
    s3_region: "eu-central-1"
    working_dir: prebuilds
    target_paths: "/librsvg"