language: node_js
branches:
  only:
  - appveyor
os:
  - osx
env:
  - CXX=g++
node_js:
  "node"
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install librsvg; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm install -g prebuild; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm install; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run prebuild; fi

deploy:
  on:
    branch: appveyor
  provider: s3
  bucket: "f3lang"
  access_key_id: $ARTIFACTS_KEY
  secret_access_key: $ARTIFACTS_SECRET
  region: "eu-central-1"
  skip_cleanup: true
  local_dir: prebuilds
  upload-dir: librsvg