language: node_js
compiler: g++-4.8
os:
  - osx
env:
  - CXX=g++-4.8
node_js:
  "node"
before_script:
  - brew update
  - brew install librsvg
  - brew install --cc=gcc-4.4 gcc@4.8
  - npm install -g prebuild
install:
  - npm install
script:
  - npm run prebuild