language: node_js
compiler: g++-4.9
os:
  - osx
env:
  - CXX=g++
node_js:
  "node"
before_script:
  - brew update
  - brew install librsvg
  - brew install gcc49 --enable-cxx
  - npm install -g prebuild
install:
  - npm install
script:
  - npm run prebuild