language: node_js
branches:
  only:
  - appveyor
os:
  - osx
env:
  - CXX=g++
node_js:
  "node"
before_script:
  - brew install librsvg
  - npm install -g prebuild
install:
  - npm install
script:
  - npm run prebuild

deploy:
  provider: s3
  bucket: "f3lang"
  access_key_id: $ARTIFACTS_KEY
  secret_access_key: $ARTIFACTS_SECRET
  region: "eu-central-1"
  skip_cleanup: true
  local_dir: prebuilds
  upload-dir: librsvg