language: node_js
os:
  - osx
env:
  - CXX=g++
node_js:
  "node"
before_script:
  - brew update
  - brew install librsvg
  - npm install -g prebuild
install:
  - npm install
script:
  - npm run prebuild