language: node_js
branches:
  only:
  - release
os:
  - osx
  - linux
env:
  - CXX=g++
node_js:
  "10.0.0"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install librsvg; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm install -g prebuild; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm install; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -i -v "${PWD}:/MyProgram" f3lang/node32bit:trusty /bin/bash -c "linux32 --32bit i386 /MyProgram/build.sh i386"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp -r prebuilds prebuilds_32; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -i -v "${PWD}:/MyProgram" ubuntu:trusty /bin/bash -c "/MyProgram/build.sh x64"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv prebuilds_32/*.tar.gz prebuilds/ ; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run prebuild; fi
  - ls prebuilds

deploy:
  on:
    branch: release
  provider: s3
  bucket: "f3lang"
  access_key_id: $ARTIFACTS_KEY
  secret_access_key: $ARTIFACTS_SECRET
  region: "eu-central-1"
  skip_cleanup: true
  local_dir: prebuilds
  upload-dir: librsvg