clone_folder: C:\librsvg-prebuilt

version: '1.0.{build}'

branches:
  only:
    - appveyor

image: Visual Studio 2015

environment:
  nodejs_version: 9
  global:
    DOWNLOAD_DIR: _download_cache
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#      VS_VER: "14"
#      PLATFORM: "x86"
#      PYTHON: C:\Python36\python.exe
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VER: "14"
      PLATFORM: "x64"
      PYTHON: C:\Python36-x64\python.exe

install:
#  - ps: IF("%PLATFORM%" -eq "x64") {Start-FileDownload 'https://s3.eu-central-1.amazonaws.com/f3lang/gtk3/gvsbuild-vs14-x64.tar.gz'}
#  - ps: IF("%PLATFORM%" -eq "x86") {Start-FileDownload 'https://s3.eu-central-1.amazonaws.com/f3lang/gtk3/gvsbuild-vs14-x86.tar.gz'}
  - curl -o gtk.tar.gz "https://s3.eu-central-1.amazonaws.com/f3lang/gtk3/gvsbuild-vs14-x64.tar.gz"
  - 7z x gtk.tar.gz -so | 7z x -si -ttar -ogtk
  - cp -r gtk\release c:\GTK
  - dir c:\GTK
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g prebuild

build_script:
  - npm run prebuild

#artifacts:
#  - path: gvsbuild-vs%VS_VER%-%PLATFORM%.tar.gz

#cache:
#  - '%DOWNLOAD_DIR%'

deploy: off

test: off